### ISSUE TITLE
Small change idea

### ISSUE THREAD

**Issue by jonrandy** [riot/logo#5]
Hi there...

To me, something just looks a little bit off with the logo. I think a really small tweak fixes it. I've attached a quick mock up - old is on the left, new on the right. What do you think?
![riot](https://user-images.githubusercontent.com/1510194/61027219-d0f0fe80-a3df-11e9-9229-6693b33f6b74.png)

**Comment by nibushibu** [comment]
@jonrandy Thank you!
Although I did not understand at first glance, I compared the left and right ones to understand the meaning you pointed out.
I will fine tune and update.

**Comment by jonrandy** [comment]
Yes. It's a very small change

**Comment by jonrandy** [comment]
?

**Comment by GianlucaGuarini** [comment]
@jonrandy please PR. I will likely not update all the Riot.js logos on the web but I will try with the official channels at least

**Comment by jonrandy** [comment]
OK - will take a look at it tomorrow hopefully

**Comment by nibushibu** [comment]
@jonrandy Sorry for not replying.

In reviewing the proposal, I came to the idea that this fix should not be reflected immediately.
That's because the new logo is already being used on various sites and tools.
I thought we should avoid making a difference between them and the official logo right away.

Also, the proposed logo will look like the inner negative space is shifted, so I would like to consider a better shape if the logo is modified.

In any case, I'd like to thank you for suggesting a better logo and for discussing it here. 
Also, I'm sorry that my full-time job was busy and I left this matter for a long time.

My logo data is made by Figma, and you can freely fork (copy) the original data from the link below. 

https://www.figma.com/file/C1DjoNmaABljfxLmwS2EGN3S/Riot.js-logo?node-id=0%3A1

**Comment by nibushibu** [comment]
@jonrandy I have created a new pull request #7 
A really small fix, but I think the logo has become a better.
Thank you very much.
